07/10/18
-------
--------
[libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: onnx/onnx.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):

The above error is cause when I have 
```
import onnx
import pyneuralnet
```

The problem is described here
https://stackoverflow.com/questions/37051635/several-shared-object-using-same-proto-leading-the-the-error-file-already-exist

For now, I don't need to import onnx and pyneuralnet together.

A robust solution would be to have neuralnet build it's own ONNX and libprotobuf, 
as is done in pytorch. Or any way where the libprotobuf linked to by `pyneuralnet'
is different from that linked to by `onnx' will resolve the problem.

